config/routes.rb
Rails.application.routes.draw do
  get 'photos/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'
  
  devise_for :users
  
  resources :posts
  resources :userparams
  resources :photos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :image, PhotoUploader

	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user

    validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
  has_one :userparam      
  has_many :posts
  has_many :photos
end

app/models/userparam.rb
class Userparam < ApplicationRecord
    belongs_to :user

    validates :firstname, :lastname, :age, presence: true
    validates :age, numericality: { only_integer: true, message: "only allows int" }
    validates :firstname, :lastname, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
    validates :lastname,:firstname, length: { in: 3..20 }

    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", small: "50x50" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
before_action :authenticate_user!, except: [:index]
	def index
		@photos = Photo.all
	end
  def new
	@photo = Photo.new
  end

  def create
	@photo = current_user.photos.build(photo_params)

	if @photo.save
		redirect_to photos_path
	end
  end

  def edit
	@photo = Photo.find_by(params[:id])
  end

  def show
  	@photo = Photo.find_by(params[:id])
  end

  def update
  	@photo = Photo.find_by(params[:id])
  	if @photo.save
  		redirect_to root_path
  	end
  end

  def destroy
  	@photo.destroy
  	redirect_to root_path
  	
  end

  private
  def photo_params
  	params.require(:photo).permit(:user_id, :title, :description,  :image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end  
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    end
    
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
private

  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end
  
  def find_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
before_action :authenticate_user!

  def new
    @userparam = Userparam.new
  end
  
  def create
    @userparam = current_user.build_userparam(profile_params)
    if @userparam.save
      redirect_to userparam_path(@userparam.id)
    else
      render 'new'
    end
    
  end
  
  def show
  end
  
  def edit
    @userparam = current_user.userparam
  end
  
  def update
    @userparam = Userparam.find_by(user_id: current_user.id)
    if @userparam.update(profile_params)
       redirect_to userparam_path(@userparam.id)
    else
      render 'edit'
    end

    
  end
  
private

  def profile_params
    params.require(:userparam).permit(:user_id, :firstname, :lastname, :age, :avatar)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<% if user_signed_in? %>
  <%= link_to "Back", root_path %> |
  <% if current_user.userparam.nil? %>
     <%= link_to "Profile", new_userparam_path %> |
  <% else %>
   <%= link_to "Profile", userparam_path(current_user.id) %> |
  <% end %>

  <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to "Login", new_user_session_path %>
<% end %>
<hr>
    <%= yield %>
  
<p>Copyright 2018 by Kusha</p>
  </body>
</html>

app/views/pages/index.html.erb
<%= link_to "Photo Gallery",  photos_path %><br />
<%= link_to "Create new post",  new_post_path %>

<% if @posts == [] %>
    <p>Create new post</p>
<% else %>
    <% @posts.each do |post| %>
       <p>User <b><%= image_tag post.user.userparam.avatar.url(:small) %> <%= post.user.email %></b> write: <br />
       <b><%= post.title %></b><br />
       <%= post.body %></p>
       <p><%= link_to "Read More", post_path(post.id) %></p>
   <hr>
    <% end %>
<% end %>

app/views/photos/edit.html.erb
<%= form_for @photo, url: photo_path(@photo.id) do |f| %>
  <%= f.text_field :title %><br />
  <%= f.text_field :description %><br />
  <%= f.file_field :body, size: "60x12" %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/photos/index.html.erb
<%= link_to 'Add new Photo', new_photo_path%>
<%if @photos ==[] %>
<p> No photo </p>
     <% else %>
<p><% @photos.each do |photo|%>
<%= photo.title%><br />
<%= photo.description%><br />
<%= image_tag(photo.image_url, size: "200x100")%></p>
	<% if photo.user_id ==current_user.id%>
	<%= link_to "Edit", edit_photo_path(photo.id)%>
	<%= link_to "Delete", photo_path(photo.id, method: :delete, data: {cofirm: "Are you sure?"})%>
		<%end%>
	<%end%>
		<% end%>

app/views/photos/new.html.erb
<%= form_for @photo, url: photos_path do |f| %>


  Photo: <%= f.file_field :image %><br />
  Title: <%= f.text_field :title %><br />
  Description: <%= f.text_field :description %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/posts/edit.html.erb
<%= form_for @post, url: post_path(@post.id) do |f| %>
  <%= f.text_field :title %><br />
  <%= f.text_area :body, size: "60x12" %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path do |f| %>

<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= f.text_field :title %><br />
  <%= f.text_area :body, size: "60x12" %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/posts/show.html.erb
User: <%= @post.user.email %><br />
Title: <%= @post.title %><br />
Body: <%= @post.body %><br />

<% if @post.user_id == current_user.id %>
<p><%= link_to "edit", edit_post_path(@post.id) %><br />
<%= link_to "delete", post_path(@post.id), method: :delete %><br /></p>
<% end %>

app/views/userparams/edit.html.erb
<%= form_for @userparam, url: userparam_path(current_user.id) do |f| %>

<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this userparam from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

	<strong>first name</strong><br>
	<%= f.text_field :firstname %><br />
	<strong>lastname</strong><br>
	<%= f.text_field :lastname %><br />
	<strong>age</strong><br>
	<%= f.text_field :age %><br />
	<p> <strong>avatar</strong><br>
	<%= f.file_field :avatar %> <br> <br></p>
	<%= f.submit "Update" %>
<% end %>

app/views/userparams/new.html.erb
<%= form_for @userparam, url: userparams_path do |f| %>

<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this userparam from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  Firsname: <%= f.text_field :firstname %><br />
  Lastname: <%= f.text_field :lastname %><br />
  Age: <%= f.text_field :age %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/userparams/show.html.erb
<%= image_tag current_user.userparam.avatar.url(:medium) %> <br>
Firstname: <%= current_user.userparam.firstname %><br />
Lastname: <%= current_user.userparam.lastname %><br />
Age: <%= current_user.userparam.age %><br />
<%= link_to "edit", edit_userparam_path(current_user.id) %><br />